version: 2
# Aqui se controlan las fuentes
sources:
  - name: raw
    schema: stackoverflow #Dataset name - BigQuery
    tables:
      - name: badges
      - name: posts_answers
      - name: posts_questions
      - name: users
